### ISSUE TITLE
What is the tentative timeline for the integration in Solana Unity SDK, without a typescript client?

### ISSUE THREAD

**Issue by lopeselio** [magicblock-labs/SOAR#6]
We're looking forward to exploring leaderboards, achievements, automated rewards distribution, and associating the same with player profiles inside [Intrant Inferis](https://x.com/IntrantInferis) game. 

Are there any game live that have implemented leaderboards, and automated incentives to players directly after the game and how are the game parameters linked to the on-chain leaderboard? 

For example if it is a racing game, then the amount of time taken could be used, if it is a combat game, then it could be the duration as well as number of kills, and accuracy per attack move. We would appreciate any examples :)

**Comment by GabrielePicco** [comment]
Hey @lopeselio , the first version has already been released: https://github.com/magicblock-labs/Solana.Unity.Soar and is included in the latest version of the SDK.

[Kamikaze Joe](https://github.com/magicblock-labs/Kamikaze-Joe) contains a simple example of score submission to the leaderboard with [CPI](https://github.com/magicblock-labs/Kamikaze-Joe/blob/main/programs/kamikazejoe/src/instructions/claim_prize_soar.rs#L47), more examples will be gradually released.  

Each leaderboard can be used with a metric, and achievements/rewards are defined on it, could be time, kills or anything.
